name: redis

services:
  redis:
    image: "redis:7.2.5-alpine"
    restart: always
    mem_limit: 512m
    ports:
      - 6379:6379
    volumes:
      - /e/dev2/docker-compose/redis/redis.conf:/etc/redis/redis.conf
    command: /usr/local/bin/redis-server /etc/redis/redis.conf
    
